config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#inicio'
  get 'visita' => 'static_pages#form_visita'
  get 'cliente' => 'static_pages#form_cliente'
  get 'ayuda' => 'static_pages#ayuda'
  get 'registrarse' => 'users#new'
  get 'loguearse' => 'sessions#new'
  post 'loguearse' => 'sessions#create'
  delete 'desloguearse' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:edit, :new, :update, :create]
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def inicio
  end

  def form_visita
  end

  def form_cliente
  end

  def ayuda
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/ayuda.html.erb
<% provide(:title, 'Ayuda') %>
<h1>Ayuda</h1>
<p>
  Por el momento, podés pedirnos ayuda llenando el formulario en <%= link_to "macherit.com", "http://www.macherit.com/#contacto" %>.
</p>

app/views/static_pages/form_cliente.html.erb
<% provide(:title, "Registrar un cliente") %>
<h1>Registrar un cliente</h1>

app/views/static_pages/form_visita.html.erb
<% provide(:title, "Registrar una visita") %>
<h1>Registrar una visita</h1>

app/views/static_pages/inicio.html.erb
<div class="center jumbotron">
  <h1>Business Intelligence</h1>
  <h3>Inteligencia para los negocios</h3>
  <div>
    <%= link_to "Registrate", registrarse_path, class: "btn btn-lg btn-primary", id: "bot_registrarse" %>
  </div>
  <div class="tareas">Desde acá podés:
    <ul>
    <li><%= link_to 'Cargar cliente', cliente_path, class: "btn btn-lg btn-secondary" %></li>
    <li><%= link_to 'Cargar visita', visita_path, class: "btn btn-lg btn-secondary" %></li>
    </ul>
  </div>
</div>