config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#inicio'
  get 'visita' => 'static_pages#form_visita'
  get 'cliente' => 'static_pages#form_cliente'
  get 'ayuda' => 'static_pages#ayuda'
  get 'registrarse' => 'users#new'
  get 'loguearse' => 'sessions#new'
  post 'loguearse' => 'sessions#create'
  delete 'desloguearse' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:edit, :new, :update, :create]
  

end

app/views/layouts/_footer.html.erb
<footer class="footer row">
  <div class="small col-md-6">
    Esta es una aplicación interna de Macher IT. Te invitamos a conocer nuestro sitio web.
    <%= link_to image_tag("macher.png", alt: "Logo de Macher IT"), 'http://macherit.com' %>
  </div>
  <div class="col-md-6">
    <ul>
      <li><%= link_to "Ayuda", ayuda_path %>
      <li><%= link_to "MacherIT.com", 'http://macherit.com' %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("cerebro.png", alt: "BusInt"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Inicio",  root_path %></li>
        <li><%= link_to "Ayuda",   ayuda_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Usuarios", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mi cuenta<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Editar", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Salir", desloguearse_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Logueate", loguearse_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="container" id="cuerpo">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>    
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>